#!/usr/bin/env python3
"""Generate the reference documentation that would otherwise drift.

The settings reference and the D-Bus contract are both already described
precisely in code — in :data:`dictatord.config.SCHEMA` and in the service
interface. Writing them out by hand guarantees they disagree with the product
within a release or two, so they are generated instead.

Run ``make docs``; CI checks the result is committed.
"""
from __future__ import annotations

import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dictatord import config as cfg  # noqa: E402
from dictatord.daemon import SHORTCUT_DESCRIPTIONS  # noqa: E402
from dictatord.errors import FaultCode  # noqa: E402

GENERATED = "<!-- Generated by scripts/gen_docs.py. Do not edit by hand. -->"


def _render(value) -> str:
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, list):
        return "`[]`" if not value else "`" + ", ".join(str(v) for v in value) + "`"
    if value == "":
        return "*(unset)*"
    return f"`{value}`"


def _constraints(field: cfg.Field) -> str:
    parts = []
    if field.choices:
        parts.append(" · ".join(f"`{c}`" for c in field.choices))
    if field.minimum is not None or field.maximum is not None:
        parts.append(f"{field.minimum:g}–{field.maximum:g}")
    return "<br>".join(parts) or "—"


def configuration() -> str:
    lines = [
        GENERATED,
        "",
        "# Configuration reference",
        "",
        "Every setting dictator has, generated from the schema that validates them.",
        "",
        "Settings are layered, lowest precedence first:",
        "",
        "1. Built-in defaults",
        "2. `/etc/dictator/config.toml` — site-wide",
        # A literal path, not the resolved one: baking $XDG_CONFIG_HOME into
        # generated output makes it differ per machine and per test run.
        "3. `~/.config/dictator/config.toml` — yours",
        "4. `DICTATOR_*` environment variables, e.g. `DICTATOR_MODEL_NAME=small`",
        "5. `--set key=value` on the daemon command line",
        "",
        "```bash",
        "dictator config list          # effective values, and where each came from",
        "dictator config set model.name small",
        "dictator config sample        # a commented file you can start from",
        "dictator config edit          # open yours in $EDITOR",
        "```",
        "",
        "Changes apply to a running daemon immediately; `dictator config set` reloads it.",
        "",
    ]
    for section in cfg.SECTIONS:
        fields = [f for f in cfg.SCHEMA if f.section == section]
        lines += [f"## `[{section}]`", "", "| Setting | Default | Values | Meaning |",
                  "|---|---|---|---|"]
        for field in fields:
            lines.append(
                f"| `{field.key}` | {_render(field.default)} | "
                f"{_constraints(field)} | {field.help} |"
            )
        lines.append("")

    lines += [
        "## Shortcuts",
        "",
        "| Id | What it does |",
        "|---|---|",
    ]
    for shortcut_id, description in SHORTCUT_DESCRIPTIONS.items():
        lines.append(f"| `{shortcut_id}` | {description} |")
    lines += [
        "",
        "```bash",
        'dictator keys set dictate "Super+d"',
        'dictator keys check "Ctrl+Alt+Space"   # validate without binding',
        "dictator keys conflicts               # what the desktop already claims",
        "```",
        "",
        "A chord needs at least one modifier that is not Shift, or it would capture",
        "ordinary typing. `dictator keys check` refuses those with a reason.",
        "",
    ]
    return "\n".join(lines) + "\n"


def faults() -> str:
    lines = [
        GENERATED,
        "",
        "# Fault codes",
        "",
        "Every failure the daemon reports carries one of these codes and a remedy.",
        "They appear in the `Fault` D-Bus signal, in the logs as `code=`, and in",
        "`dictator stats` counters. The codes are stable; the messages are not.",
        "",
        "| Code | Area |",
        "|---|---|",
    ]
    areas = {
        "platform": "Display server, shortcuts, injection",
        "audio": "Capture devices and streams",
        "asr": "Speech model loading and decoding",
        "memory": "Transcript store",
        "config": "Configuration files",
        "session": "Dictation lifecycle",
        "internal": "Unclassified — report these",
    }
    for code in FaultCode:
        area = code.value.split(".", 1)[0]
        lines.append(f"| `{code.value}` | {areas.get(area, area)} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def dbus_api() -> str:
    from dictatord import service

    lines = [
        GENERATED,
        "",
        "# D-Bus API",
        "",
        f"- **Bus name** `{service.BUS_NAME}` (session bus)",
        f"- **Object path** `{service.OBJECT_PATH}`",
        f"- **Interface** `{service.INTERFACE}`",
        "",
        "This is the product's real API. The `dictator` command is an ordinary",
        "client with no privileged access, and any UI would be another one.",
        "",
        "```bash",
        "busctl --user introspect com.watkinslabs.Dictator1 /com/watkinslabs/Dictator1",
        "```",
        "",
    ]

    interface = service.DictatorInterface
    methods, signals, properties = [], [], []
    for name, member in vars(interface).items():
        if name.startswith("_"):
            continue
        target = getattr(member, "__func__", member)
        doc = (inspect.getdoc(target) or "").split("\n\n")[0].replace("\n", " ")
        annotations = getattr(target, "__annotations__", {})
        signature = ", ".join(
            f"{k}: {v}" for k, v in annotations.items() if k != "return"
        )
        returns = annotations.get("return", "")
        if "__DBUS_METHOD" in getattr(member, "__dict__", {}):
            methods.append((name, signature, returns, doc))
        elif "__DBUS_SIGNAL" in getattr(member, "__dict__", {}):
            signals.append((name, signature, doc))
        elif member.__class__.__name__ == "_Property" or hasattr(member, "prop_getter"):
            properties.append((name, returns, doc))

    lines += ["## Methods", "", "| Method | Arguments | Returns |", "|---|---|---|"]
    for name, signature, returns, _doc in sorted(methods):
        lines.append(f"| `{name}` | {f'`{signature}`' if signature else '—'} | "
                     f"{f'`{returns}`' if returns else '—'} |")

    lines += ["", "## Signals", "", "| Signal | Arguments |", "|---|---|"]
    for name, signature, _doc in sorted(signals):
        lines.append(f"| `{name}` | {f'`{signature}`' if signature else '—'} |")

    lines += [
        "",
        "## Notes",
        "",
        "- `Toggle` returns `(id, listening)`. The flag is what distinguishes",
        "  starting from stopping; an id alone cannot.",
        "- `Partial` carries `stable_chars`: that many leading characters have",
        "  survived a re-decode and will not change. Render the rest as",
        "  provisional, or the live view flickers.",
        "- `Partial` is for display only. Delivery uses `Final`.",
        "- `Level` fires at 50 Hz with peak, RMS, a clipping flag and eight",
        "  log-spaced bands — enough for a VU meter, a waveform or a spectrum,",
        "  from one signal.",
        "- Arguments are bounded and validated: the bus is a trust boundary, and",
        "  any process on it can call this.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    written = []
    for name, generator in (
        ("configuration.md", configuration),
        ("dbus-api.md", dbus_api),
        ("faults.md", faults),
    ):
        path = docs / name
        content = generator()
        if not path.is_file() or path.read_text() != content:
            path.write_text(content)
            written.append(name)
    print(f"generated {len(written)} file(s)" + (f": {', '.join(written)}" if written else " (all current)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
